#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y mosquitto
  - git clone https://github.com/uilianries/3rdParty.git && cd 3rdParty && sudo dpkg -i libpoco_1.7-amd64.deb && cd ..
  - git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && make && sudo make install
  - cd ../.. && rm -rf googletest

script:
  - mkdir build && cd build && cmake .. && make
  - sudo make install
  - test/TestIoTMQTT

branches:
  only:
    - master
    - develop
