#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y mosquitto
  - sudo pip install conan

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. 
  - cmake --build .
  - sudo make install
  - bin/TestIoTMQTT

branches:
  only:
    - master
    - develop
